# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Clouded thoughts
tagline:          'things about devops and clouds'
description:      'written by Jakub Woźniak, Cloud Architect from Poland ;)'
url:              http://mescam.github.io
baseurl:          /

author:
  name:           'Jakub Woźniak'
  url:            http://wozniak.im

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
