baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jakub Woźniak'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
My name is Jakub Woźniak and I’m a Software and Cloud Architect with over 10 years of experience, currently serving as the CTO of Software Services at Nordcloud, an IBM Company. My career has been a blend of hands-on technical expertise and strategic leadership. I specialize in cloud architecture, particularly across AWS, GCP, and Azure, where I design and implement scalable, cloud-native solutions.

Beyond technical execution, my role involves guiding teams, driving innovation, and aligning technology strategies with business objectives. My expertise spans DevOps, SRE, and Platform Engineering, enabling organizations to achieve efficiency, reliability, and growth.

In addition to my professional life, I enjoy flight simulation, sport shooting, 3D printing, microelectronics, and crafting the perfect cup of coffee.

Whether you’re here to learn, collaborate, or connect, I’m glad you stopped by."""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/wozniakjakub"

[[params.social]]
name = "medium"
url = "https://medium.com/@jakubwozniak"

[[params.social]]
name = "github"
url = "https://github.com/mescam"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
